### ISSUE TITLE
Using deprecated class Objects.ToStringHelper

### ISSUE THREAD

**Issue by ghost** [smartcanvas/java-sdk#1]
Hello,

This package is using the deprecated class `Objects.ToStringHelper` in [many files](https://github.com/smartcanvas/java-sdk/search?q=Objects.toStringHelper&type=Code). This class is marked as deprecated and it is [scheduled for removal in June 2016](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Objects.ToStringHelper.html). The recommended class to be used is `MoreObjects.ToStringHelper`.

**Comment by fabito** [comment]
Note that we are not importing the `Objects` class from `Guava`.
Instead we are using a repackaged one from the package `com.google.api.client.util`, which follows a different deprecaton policy.

Thanks for the heads up anyway!

**Comment by ghost** [comment]
@fabito, you are right. You are not importing from `Guava` but from `com.google.api.client.util`. But the fact is that it is a `proxy` to the `Guava Objects` implementation and that seems a little outdated. I just created the issue because as the package is young maybe the head's up is a little valid.

Regards.
